### ISSUE TITLE
unrecognized import path "golang.org/x/image/math/fixed" 

### ISSUE THREAD

**Issue by zhuxiujia** [hanguofeng/gocaptcha#14]
package golang.org/x/image/math/fixed: unrecognized import path "golang.org/x/image/math/fixed" (https fetch: Get https://golang.org/x/image/math/fixed?go-get=1: dial tcp 216.239.37.1:443: connectex: A connection attempt failed because the connected party did not properly respond after a period o
f time, or established connection failed because connected host has failed to respond.)
package golang.org/x/image/font: unrecognized import path "golang.org/x/image/font" (https fetch: Get https://golang.org/x/image/font?go-get=1: dial tcp 216.239.37.1:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or establi
shed connection failed because connected host has failed to respond.)

**Comment by hanguofeng** [comment]
I think this is because some sites are blocked, you may use a proxy to install.
