### ISSUE TITLE
为何不考虑同一KEY刷新验证码时显示不同验证码字符串呢

### ISSUE THREAD

**Issue by xdxiaodong** [hanguofeng/gocaptcha#8]
现在是使用同一KEY刷新验证码图片时，只是变换了背景，验证码图片上显示的字符串被未更换，为什么不考虑同一KEY刷新验证码图片时既变换背景又变换验证码图片上显示的字符串呢？

**Comment by hanguofeng** [comment]
最初的设计是为了简单，这样在刷新图片的时候不需要重新生成内容字符串并存储。
如果需要刷新图片内容，可以重新生成一个key

**Comment by xdxiaodong** [comment]
会考虑增加刷新图片重新生成内容字符串接口吗？

**Comment by xdxiaodong** [comment]
已自己实现接口
