### ISSUE TITLE
为何验证字符不居中，总是对齐左边

### ISSUE THREAD

**Issue by ddaddca** [hanguofeng/gocaptcha#9]
<img width="113" alt="aaaca" src="https://cloud.githubusercontent.com/assets/15108279/14845468/01b8d1bc-0c91-11e6-96cc-83211c63e900.png">

如图，配置文件如下

> [captcha]
> word_dict=./resources/font/en_char
> life_time=5m
> 
> [store]
> engine=buildin
> @servers=127.0.0.1:11211
> gc_probability=1
> gc_divisor=100
> 
> [image]
> width=120
> height=40
> font_size=24
> @font_files=./resources/font/zpix.ttf
> 
> [filter]
> @open_filter=ImageFilterNoiseLine
> @open_filter=ImageFilterNoisePoint
> @open_filter=ImageFilterStrike
> 
> [ImageFilterNoiseLine]
> Num=10
> [ImageFilterNoisePoint]
> Num=10

请问有没有地方可以配置图片颜色和文字位置，谢谢

**Comment by hanguofeng** [comment]
图片颜色是随机的。
图片位置是左上角开始绘制的，你可以调整width/heigh直至合适的尺寸，来使得图片居中。
